// have groups?
const categoryOptions = [
  { value: 'action', label: 'Action' }, //games
  { value: 'adventure', label: 'Adventure' },
  { value: 'arcade', label: 'Arcade' },
  { value: 'board', label: 'Board' },
  { value: 'card', label: 'Card' },
  { value: 'casino', label: 'Casino' },
  { value: 'casual', label: 'Casual' },
  { value: 'educational', label: 'Educational' },
  { value: 'music', label: 'Music' },
  { value: 'puzzle', label: 'Puzzle' },
  { value: 'racing', label: 'Racing' },
  { value: 'role playing', label: 'Role Playing' },
  { value: 'simulation', label: 'Simulation' },
  { value: 'sports', label: 'Sports' },
  { value: 'strategy', label: 'Strategy' },
  { value: 'trivia', label: 'Trivia' },
  { value: 'word', label: 'Word' },
  { value: 'family', label: 'Family' },

  { value: 'art & design', label: 'Art & Design' }, //apps
  { value: 'auto & vehicles', label: 'Auto & Vehicles' },
  { value: 'beauty', label: 'Beauty' },
  { value: 'books & reference', label: 'Books & Reference' },
  { value: 'business', label: 'Business' },
  { value: 'comics', label: 'Comics' },
  { value: 'communication', label: 'Communication' },
  { value: 'dating', label: 'Dating' },
  { value: 'education', label: 'Education' },
  { value: 'entertainment', label: 'Entertainment' },
  { value: 'events', label: 'Events' },
  { value: 'finance', label: 'Finance' },
  { value: 'food & drink', label: 'Food & Drink' },
  { value: 'health & fitness', label: 'Health & Fintess' },
  { value: 'house & home', label: 'House & Home' },
  { value: 'libraries & demo', label: 'Libraries & Demo' },
  { value: 'lifestyle', label: 'Lifestyle' },
  { value: 'maps & navigation', label: 'Maps & Navigation' },
  { value: 'medical', label: 'Medical' },
  { value: 'music & auto', label: 'Music & Auto' },
  { value: 'news & magazines', label: 'News & Magazines' },
  { value: 'parenting', label: 'Parenting' },
  { value: 'personalization', label: 'Personalization' },
  { value: 'photography', label: 'Photography' },
  { value: 'productivity', label: 'Productivity' },
  { value: 'shopping', label: 'Shopping' },
  { value: 'social', label: 'Social' },
  { value: 'sports', label: 'Sports' },
  { value: 'tools', label: 'Tools' },
  { value: 'travel & location', label: 'Travel & Location' },
  { value: 'video players', label: 'Video Players' },
  { value: 'weather', label: 'Weather' }
]

export default categoryOptions
